services:
  - type: web
    name: mcq-quiz-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - fromGroup: mcq-quiz-secrets
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
